version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: chatbi-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatbi_db
      MYSQL_USER: chatbi_user
      MYSQL_PASSWORD: chatbi_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatbi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Ollama Service
  ollama:
    image: ollama/ollama:latest
    container_name: chatbi-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - chatbi-network
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ChatBI Backend
  backend:
    build:
      context: ./chatbi-server
      dockerfile: Dockerfile
    container_name: chatbi-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://chatbi_user:chatbi_password@mysql:3306/chatbi_db
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama2
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=False
    depends_on:
      mysql:
        condition: service_healthy
      ollama:
        condition: service_healthy
    networks:
      - chatbi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ChatBI Frontend
  frontend:
    build:
      context: ./chatbi-ui
      dockerfile: Dockerfile
    container_name: chatbi-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - chatbi-network

volumes:
  mysql_data:
  ollama_data:

networks:
  chatbi-network:
    driver: bridge